# Generated by Django 5.2.6 on 2025-09-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0002_remove_attendance_hours_worked_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
