# Generated by Django 5.2.6 on 2025-09-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0003_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
